# Generated by Django 5.1.4 on 2024-12-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='save_to_db',
            field=models.BooleanField(default=True),
        ),
    ]
